In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 9, 1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 9. , 1. ])

In [6]:
arr1.shape

(5,)

In [7]:
data2 = [[1, 2, 3, 4],
         [5, 6, 7, 8]]

In [8]:
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

In [11]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.arange((30))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [22]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)

In [23]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [24]:
arr.dtype

dtype('int64')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr

array([1., 2., 3., 4., 5.])

In [28]:
float_arr.dtype

dtype('float64')

In [29]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [30]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]], dtype=np.float64)

In [31]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [34]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [35]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [36]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [38]:
arr1 * 3

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [39]:
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [40]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [41]:
arr = np.arange(10)

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5]

5

In [46]:
arr[5:8]

array([5, 6, 7])

In [47]:
arr[5:8] = 12

In [48]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [49]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

In [51]:
arr2d[2, :]

array([ 9, 10, 11, 12])

In [53]:
arr2d [1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr2d[:, 3]

array([ 4,  8, 12, 16])

In [57]:
arr2d[:, :3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [58]:
arr2d[3, 2]

15

In [60]:
arr2d[:2, 1:3] = 0

In [61]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [77]:
names = np.array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung','Kilho', 'Kilho'])
data = np.random.randn(7, 4)

In [78]:
names

array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung', 'Kilho',
       'Kilho'], dtype='<U7')

In [75]:
data

array([[ 0.47272191,  0.84103258, -0.27468381,  1.00972035],
       [-0.38018438,  1.33955863,  1.02775418, -0.83774037],
       [ 1.28994002, -0.13621273,  0.32236756,  0.74282286],
       [ 2.64024035, -0.53347533,  0.36367962,  0.2233165 ],
       [-0.78308924, -1.15775599, -0.68680773,  0.61317067],
       [-0.76216337, -0.45095559, -1.16721171, -0.58314923],
       [ 0.44662309, -0.67800056,  0.28901782, -1.83682796]])

In [79]:
names == 'Charles'

array([ True, False, False,  True, False, False, False])

In [80]:
data[names == 'Charles', :]

array([[ 1.48199285, -0.22750543, -0.04633991, -2.01943372],
       [ 0.89968949, -0.78176175,  0.31932753,  2.45463965]])

In [82]:
data[names == 'Kilho', :]

array([[-0.63156313,  0.9508309 ,  0.01734689, -0.08769439],
       [ 1.08188938, -0.74934177,  1.63972365,  0.65856265],
       [-0.28198815, -0.30434443,  1.24271379,  0.37474001]])

In [84]:
data[(names == 'Charles') | (names == 'Kilho'), :]

array([[ 1.48199285, -0.22750543, -0.04633991, -2.01943372],
       [-0.63156313,  0.9508309 ,  0.01734689, -0.08769439],
       [ 0.89968949, -0.78176175,  0.31932753,  2.45463965],
       [ 1.08188938, -0.74934177,  1.63972365,  0.65856265],
       [-0.28198815, -0.30434443,  1.24271379,  0.37474001]])

In [85]:
data[:, 3]

array([-2.01943372, -0.08769439,  1.48599747,  2.45463965, -1.60613128,
        0.65856265,  0.37474001])

In [86]:
data[:, 3] < 0

array([ True,  True, False, False,  True, False, False])

In [87]:
data[data[:, 3] < 0, :]

array([[ 1.48199285, -0.22750543, -0.04633991, -2.01943372],
       [-0.63156313,  0.9508309 ,  0.01734689, -0.08769439],
       [ 1.08575079, -0.57835251,  0.02820704, -1.60613128]])

In [88]:
data[data[:, 3] < 0, :] = 0

In [93]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.18633775,  0.41617979, -1.2049514 ,  1.48599747],
       [ 0.89968949, -0.78176175,  0.31932753,  2.45463965],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.08188938, -0.74934177,  1.63972365,  0.65856265],
       [-0.28198815, -0.30434443,  1.24271379,  0.37474001]])

array 관련 함수 사용하기

In [91]:
arr = np.arange(1, 10)

In [92]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.sqrt(arr) #제곱근

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [105]:
x = np.random.randn(8)
y = np.random.randn(8)

In [106]:
x

array([ 0.00356984, -0.99835006, -0.90306416,  0.17522081,  1.12435719,
       -0.28790341, -0.74385479, -0.07164091])

In [107]:
y

array([ 0.01406708, -1.16382759,  1.04521764,  1.8617415 ,  1.33493924,
        0.47691868, -0.63077315,  0.81776525])

In [109]:
np.maximum(x, y) #두 array를 비교하여 각 위치에서 더 큰 값을 반환

array([ 0.01406708, -0.99835006,  1.04521764,  1.8617415 ,  1.33493924,
        0.47691868, -0.63077315,  0.81776525])

In [110]:
np.minimum(x, y)

array([ 0.00356984, -1.16382759, -0.90306416,  0.17522081,  1.12435719,
       -0.28790341, -0.74385479, -0.07164091])

In [111]:
arr = np.random.randn(5, 4)

In [112]:
arr

array([[ 0.2513423 ,  0.54359126, -1.10609727,  0.7427542 ],
       [ 1.30820459,  0.35414508, -1.22575003,  0.17994941],
       [ 1.07805093,  0.84016609, -1.2077514 ,  0.81140533],
       [ 0.70785875,  0.30793275,  0.03611686,  1.63766649],
       [ 0.30942214, -0.08151411,  0.02318785, -1.04537712]])

In [115]:
arr.sum()

4.465304088748881

In [116]:
arr.mean()

0.22326520443744405

In [117]:
arr.sum(axis=0) # 각 열의 합

array([ 3.65487871,  1.96432107, -3.480294  ,  2.32639831])

In [118]:
arr.sum(axis=1) # 각 행의 합

array([ 0.43159049,  0.61654905,  1.52187095,  2.68957484, -0.79428124])

In [119]:
arr > 0

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False]])

In [121]:
(arr > 0). sum()

15

In [122]:
arr = np.random.randn(8)

In [123]:
arr

array([ 1.52055037, -0.98966044, -1.19302639, -0.35966227, -1.33939231,
        1.36017298, -0.91436383, -0.92815317])

In [124]:
np.sort(arr)

array([-1.33939231, -1.19302639, -0.98966044, -0.92815317, -0.91436383,
       -0.35966227,  1.36017298,  1.52055037])

In [125]:
np.sort(arr)[::-1] #내림차순을 만드는 꼼수

array([ 1.52055037,  1.36017298, -0.35966227, -0.91436383, -0.92815317,
       -0.98966044, -1.19302639, -1.33939231])

In [126]:
arr = np.random.randn(5, 3)

In [127]:
arr

array([[ 1.96644015,  0.14281382, -0.28431082],
       [ 0.09351375,  0.88197454, -0.8965169 ],
       [-0.15554591, -0.05883439,  1.17727857],
       [ 1.60971836,  0.57202415,  1.53847538],
       [-2.12198645, -1.08762009,  0.28432664]])

In [128]:
np.sort(arr, axis=0)

array([[-2.12198645, -1.08762009, -0.8965169 ],
       [-0.15554591, -0.05883439, -0.28431082],
       [ 0.09351375,  0.14281382,  0.28432664],
       [ 1.60971836,  0.57202415,  1.17727857],
       [ 1.96644015,  0.88197454,  1.53847538]])

In [129]:
np.sort(arr, axis=1)

array([[-0.28431082,  0.14281382,  1.96644015],
       [-0.8965169 ,  0.09351375,  0.88197454],
       [-0.15554591, -0.05883439,  1.17727857],
       [ 0.57202415,  1.53847538,  1.60971836],
       [-2.12198645, -1.08762009,  0.28432664]])

In [130]:
large_arr = np.random.randn(150)

In [131]:
large_arr

array([ 1.6744176 , -1.57182792,  1.28536425,  1.15569242,  0.09434719,
       -0.22169994, -1.14074679, -0.49690192, -1.12841948, -0.14437197,
       -2.28444283, -1.12911454,  0.78575106,  1.19697136, -0.78371243,
       -0.25770164,  0.64860919, -1.64070702, -0.17332001, -0.86391777,
       -0.09170184, -0.12900729, -1.19715102,  0.63452632, -0.0920813 ,
       -0.50704586,  1.28827727,  2.30002546, -1.2731986 , -0.11547501,
       -1.15342671,  0.8380632 , -1.30902647, -0.66353757, -1.17595683,
        2.06062675, -2.75185435, -0.92778462, -1.15133601, -0.90800487,
       -1.57949325, -0.05592939, -1.06487417, -1.24883692, -1.68515126,
       -0.82118337, -0.61571291, -0.40026838,  1.69451534, -0.58126007,
        0.5439397 , -0.64899345,  0.10063943, -1.58134455,  0.70402058,
        0.40144158, -0.64077076,  0.70498971, -0.47351399, -1.53577649,
        0.61748063, -0.2030914 ,  1.52831184, -0.85420362, -1.27631593,
       -0.09165397, -0.38971418, -0.54064906, -0.60347044, -0.04

In [132]:
np.sort(large_arr)[::-1]

array([ 2.41296872,  2.30002546,  2.06062675,  2.02859563,  1.89626728,
        1.88875653,  1.69451534,  1.6744176 ,  1.59685416,  1.52831184,
        1.52320073,  1.51452806,  1.47961374,  1.42131192,  1.41556991,
        1.37445254,  1.35402752,  1.28827727,  1.28536425,  1.19697136,
        1.15569242,  1.02817761,  0.96549446,  0.95803699,  0.94674273,
        0.92609629,  0.90577089,  0.8380632 ,  0.78575106,  0.73707189,
        0.72821505,  0.70511567,  0.70498971,  0.70402058,  0.68703342,
        0.65766263,  0.64860919,  0.63452632,  0.61748063,  0.60063977,
        0.60005709,  0.59017067,  0.5439397 ,  0.52527567,  0.49784504,
        0.4423011 ,  0.42899998,  0.42374345,  0.42257634,  0.41788867,
        0.41152954,  0.40144158,  0.38045378,  0.31000253,  0.29738777,
        0.28579557,  0.26801421,  0.25437103,  0.24778098,  0.22665591,
        0.18419944,  0.15436796,  0.14653036,  0.13523988,  0.12249756,
        0.10741794,  0.10063943,  0.09434719,  0.08893931,  0.01

In [134]:
np.sort(large_arr)[::-1][int(0.05 * len(large_arr))]

1.6744175956471226

In [135]:
names = np.array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung', 'Kilho', 'Kilho'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [136]:
np.unique(names)

array(['Charles', 'Hayoung', 'Kilho'], dtype='<U7')

In [138]:
np.unique(ints)

array([1, 2, 3, 4])